import tkinter as tk
from tkinter import filedialog
import csv
import os

def select_txt_files():
    root = tk.Tk()
    root.withdraw()
    file_paths = filedialog.askopenfilenames(
        title="Please select 1 or 2 .txt files of Id@Vg and/or Id@Vd data about one single device generated by LTSpice",
        filetypes=[("Text files", "*.txt")]
    )
    return list(file_paths)

def parse_ltspice_txt(txt_path, output_rows):
    with open(txt_path, 'r') as f:
        lines = f.readlines()

    current_block = []
    current_label = None

    for line in lines:
        line = line.strip()
        if line.startswith("Step Information:"):
            # Write previous block if exists
            if current_block and current_label:
                for row in current_block:
                    row[0] = current_label
                    output_rows.append(row)
            # Determine label for this block
            info = line.split(":")[1].strip()
            if info.startswith("Vgs"):
                current_label = "Id@V_drain_bias"
            elif info.startswith("Vds"):
                current_label = "Id@V_gate_bias"
            else:
                current_label = "Id"
            current_block = []
        elif line and not line.startswith("*") and not line.startswith(".") and not line.startswith("Step Information:"):
            parts = line.split()
            if len(parts) >= 4:
                row = [None, parts[1], parts[2], parts[3]]
                current_block.append(row)
    # Write last block if exists
    if current_block and current_label:
        for row in current_block:
            row[0] = current_label
            output_rows.append(row)

if __name__ == "__main__":
    # User selects one or more .txt files
    txt_files = select_txt_files()
    if not txt_files:
        print("No file selected.")
        exit()

    # Output file path
    output_csv = os.path.join(os.path.dirname(txt_files[0]), "id_vds_ltspice.csv")

    # Explicitly define the header
    ref_header = ["Title", "Vgs", "Vds", "Ids"]

    # Collect all rows from all selected files
    output_rows = []
    for txt_file in txt_files:
        parse_ltspice_txt(txt_file, output_rows)

    # Write to CSV
    with open(output_csv, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(ref_header)
        for row in output_rows:
            writer.writerow(row)

    print(f"Conversion complete. Output saved to: {output_csv}")